from typing import TypedDict

movieparse_types = TypedDict(
    "movieparse_types",
    {
        "cast.adult": bool,
        "cast.gender": int,
        "cast.id": int,
        "cast.known_for_department": str,
        "cast.name": str,
        "cast.original_name": str,
        "cast.popularity": float,
        "cast.profile_path": str,
        "cast.cast_id": str,
        "cast.character": str,
        "cast.credit_id": int,
        "cast.order": int,
        "collection.id": int,
        "collection.name": str,
        "collection.poster_path": str,
        "collection.backdrop_path": str,
        "crew.adult": bool,
        "crew.gender": int,
        "crew.id": int,
        "crew.known_for_department": str,
        "crew.name": str,
        "crew.original_name": str,
        "crew.popularity": float,
        "crew.profile_path": str,
        "crew.credit_id": int,
        "crew.department": str,
        "crew.job": str,
        "genres.id": int,
        "genres.name": str,
        "production_companies.id": int,
        "production_companies.logo_path": str,
        "production_companies.name": str,
        "production_companies.origin_country": str,
        "production_countries.iso_3166_1": str,
        "production_countries.name": str,
        "spoken_languages.english_name": str,
        "spoken_languages.iso_3166_1": str,
        "spoken_languages.name": str,
        "adult": bool,
        "backdrop_path": str,
        "budget": int,
        "homepage": str,
        "imdb_id": str,
        "original_language": str,
        "original_title": str,
        "overview": str,
        "popularity": float,
        "poster_path": str,
        "release_date": str,
        "revenue": int,
        "runtime": int,
        "status": str,
        "tagline": str,
        "title": str,
        "video": str,
        "vote_average": float,
        "vote_count": int,
    },
    total=False,
)
